# Generated by Django 2.2.8 on 2020-02-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fees', models.IntegerField()),
                ('course_art', models.FileField(upload_to='cover')),
                ('categories', models.CharField(choices=[('ED', 'Engineering  Design'), ('WT', 'Welding Techniques'), ('IS', 'Information Security'), ('BM', 'Business Management'), ('BP', 'Bio Pharmacy'), ('IT', 'Information Technology')], max_length=100)),
                ('duration', models.CharField(max_length=70)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='course_joined', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentcourse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
