# Generated by Django 3.0.5 on 2020-04-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200331_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('sub_title', models.CharField(max_length=127)),
                ('category', models.CharField(choices=[('Engineering  Design', 'Engineering  Design'), ('Welding Techniques', 'Welding Techniques'), ('Information Security', 'Information Security'), ('Business Management', 'Business Management'), ('Bio Pharmacy', 'Bio Pharmacy'), ('Information Technology', 'Information Technology')], default='General Education', max_length=127)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('is_official', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('students', models.ManyToManyField(to='classroom.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Teacher')),
            ],
            options={
                'db_table': 'at_courses',
            },
        ),
    ]
