# Generated by Django 3.0.5 on 2020-04-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_coursepreview_homepagecoursepreview_homepagepartner_homepagetoppickcourse_hometeammember_landpagecon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePreview',
        ),
        migrations.DeleteModel(
            name='HomepageCoursePreview',
        ),
        migrations.DeleteModel(
            name='HomepagePartner',
        ),
        migrations.RemoveField(
            model_name='homepagetoppickcourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='HomeTeamMember',
        ),
        migrations.DeleteModel(
            name='LandpageContactMessage',
        ),
        migrations.DeleteModel(
            name='HomepageTopPickCourse',
        ),
    ]
