# Generated by Django 3.0.5 on 2020-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_landpageteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandpageCoursePreview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_filename', models.CharField(max_length=31)),
                ('title', models.CharField(max_length=127)),
                ('category', models.CharField(max_length=31)),
            ],
            options={
                'db_table': 'at_course_previews',
            },
        ),
        migrations.DeleteModel(
            name='LandpageTeamMember',
        ),
    ]
