# Generated by Django 3.0.5 on 2020-04-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20200403_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Good',
        ),
    ]
