# Generated by Django 3.0.5 on 2020-04-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_delete_good'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
