# Generated by Django 3.0.5 on 2020-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_course_coursepreview_landpagecontactmessage_landpagecoursepreview_landpagepartner_landpageteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Display the questions in a random order or as they are set?', verbose_name='Random Order'),
        ),
    ]
