# Generated by Django 3.0.5 on 2020-04-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_quiz_random_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subject', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject', verbose_name='Subject')),
            ],
        ),
    ]
