# Generated by Django 3.0.5 on 2020-04-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_subsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sub_subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subjects', to='classroom.SubSubject'),
        ),
    ]
