# Generated by Django 3.0.5 on 2020-04-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_question_sub_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='sub_subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='classroom.SubSubject'),
        ),
    ]
