# Generated by Django 3.0.5 on 2020-05-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_profile'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_messages')),
                ('description', models.TextField()),
                ('student_name', models.CharField(max_length=200)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
            ],
        ),
    ]
